import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagedesktop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePageDesktop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sendreceivemoneydesktoptwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SendReceiveMoneyDesktopTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sendreceivemoneydesktop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SendReceiveMoneyDesktop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sendreceivemoneydesktopthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SendReceiveMoneyDesktopThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sendreceivemoneydesktopone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SendReceiveMoneyDesktopOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sendreceivemoneydesktopfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SendReceiveMoneyDesktopFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/exchangedesktop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ExchangeDesktop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/macbookpro16one" style={{ color: "#87CEFA", textDecoration: "none" }}>
            MacBookPro16One
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
